# Generated by Django 5.1.3 on 2024-11-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='details',
            field=models.TextField(default='Click Here...'),
        ),
        migrations.AlterField(
            model_name='management',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
